# Generated by Django 5.0.6 on 2024-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salary_total_payment_alter_salary_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
    ]
