# Generated by Django 5.0.6 on 2024-06-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_salary_week_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='week_start',
        ),
    ]
