# Generated by Django 5.0.6 on 2024-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_remove_salary_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='value_hour',
            field=models.FloatField(default=0),
        ),
    ]
